export enum UsersEvents {
    FOLLOW = 'USERS/FOLLOW',
    UNFOLLOW = 'USERS/UNFOLLOW',
    SET_USERS = 'USERS/SET_USERS',
    SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE',
    SET_TOTAL_COUNT_USERS = 'USERS/SET_TOTAL_COUNT_USERS',
    USERS_IS_LOADING = 'USER/IS_LOADING',
    SET_FOLLOWING_PROGRESS = 'SET_FOLLOWING_PROGRESS'
}

export enum ProfilePageEvents {
    ADD_POST = 'PROFILE/ADD_POST',
    SET_PROFILE = 'PROFILE/SET_PROFILE',
    PROFILE_IS_LOADING = 'PROFILE_IS_LOADING',
    SET_STATUS = 'PROFILE/SET_STATUS'
}

export enum AuthEvents {
    SET_USER_DATA = 'SET_USER_DATA'
}


export enum DialogsEvents {
    ADD_DIALOG_MESSAGE = 'ADD_DIALOG_MESSAGE'
}

export enum AppEvents {
    SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE',
    SET_IS_LOADING = 'SET_IS_LOADING',
    SET_SUCCESS_INITIALIZE= 'SET_SUCCESS_INITIALIZE'
}